import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://192.168.29.107:8080/login');
  await page.getByRole('textbox', { name: 'Username (First Name)' }).click();
  await page.getByRole('textbox', { name: 'Username (First Name)' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Username (First Name)' }).fill('PRAVEENBALAJI');
  await page.getByRole('textbox', { name: 'Username (First Name)' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password (ID)' }).fill('PHPS03');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByText('/ 9').click();
  await page.getByText('9', { exact: true }).click();
  await page.getByText('0').nth(1).click();
  await page.getByRole('link', { name: 'Free A Tap to assign' }).click();
  await page.getByRole('textbox', { name: 'Name', exact: true }).click();
  await page.getByRole('textbox', { name: 'Name', exact: true }).fill('SANJI');
  await page.locator('label:nth-child(3) > .glass').dblclick();
  await page.getByRole('textbox', { name: 'Mobile' }).fill('8610588775');
  await page.getByRole('button').nth(4).dblclick();
  await page.getByRole('button').nth(3).click();
  await page.getByRole('button', { name: 'Vijayakumar' }).click();
  await page.getByRole('button', { name: 'Vijayakumar' }).press('ArrowRight');
  await page.getByRole('button', { name: 'OK — Start Session' }).click();
  await page.getByRole('button', { name: '+' }).nth(2).click();
  await page.getByRole('button', { name: '+', exact: true }).nth(5).click();
  await page.getByRole('button', { name: '+' }).nth(3).click();
  await page.getByRole('button', { name: '+' }).nth(4).click();
  await page.getByRole('button', { name: 'Left' }).first().click();
  await page.getByRole('button', { name: 'Add Kid (₹99)' }).click();
  await page.getByRole('button', { name: 'Add Adult (₹149)' }).click();
  await page.getByRole('button', { name: 'Add Table Now' }).click();
  await page.getByRole('button', { name: 'B', exact: true }).click();
  await page.getByRole('button', { name: 'Add', exact: true }).click();
  await page.getByRole('button', { name: 'End Session & Generate Bill' }).click();
  await page.getByRole('button', { name: 'Print' }).click();
  await page.getByRole('button', { name: 'Dashboard' }).click();
  await page.getByRole('button', { name: 'Toggle theme' }).click();
  await page.getByRole('button', { name: 'Toggle theme' }).click();
  await page.getByText('0').nth(2).click();
  await page.getByText('0').nth(1).click();
  await page.getByRole('link', { name: 'History' }).click();
  await page.goto('http://192.168.29.107:8080/');
});