/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewRouteImport } from './routes/new'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionIdRouteImport } from './routes/session.$id'
import { Route as BillIdRouteImport } from './routes/bill.$id'

const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionIdRoute = SessionIdRouteImport.update({
  id: '/session/$id',
  path: '/session/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BillIdRoute = BillIdRouteImport.update({
  id: '/bill/$id',
  path: '/bill/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/bill/$id': typeof BillIdRoute
  '/session/$id': typeof SessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/bill/$id': typeof BillIdRoute
  '/session/$id': typeof SessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/bill/$id': typeof BillIdRoute
  '/session/$id': typeof SessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/history' | '/login' | '/new' | '/bill/$id' | '/session/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/history' | '/login' | '/new' | '/bill/$id' | '/session/$id'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/login'
    | '/new'
    | '/bill/$id'
    | '/session/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  NewRoute: typeof NewRoute
  BillIdRoute: typeof BillIdRoute
  SessionIdRoute: typeof SessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$id': {
      id: '/session/$id'
      path: '/session/$id'
      fullPath: '/session/$id'
      preLoaderRoute: typeof SessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bill/$id': {
      id: '/bill/$id'
      path: '/bill/$id'
      fullPath: '/bill/$id'
      preLoaderRoute: typeof BillIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  NewRoute: NewRoute,
  BillIdRoute: BillIdRoute,
  SessionIdRoute: SessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
